## Kubernetes Manifest file - Service
apiVersion: v1
kind: Service
metadata:
  name: brownbag
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    name: brownbag