# Kubernetes Manifest file - Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpv2-deployment
spec:
  selector:
    matchLabels:
      app: testphp
  replicas: 1
  template:
    metadata:
      labels:
        app: testphp
    spec:
      containers:
      - name: testphp
        image: testacr03.azurecr.io/phpv2:latest
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume
          mountPath: /"/mnt/azure"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk
