# Kubernetes Manifest file - Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: testphp
  replicas: 4
  template:
    metadata:
      labels:
        app: testphp
    spec:
      containers:
      - name: testphp
        image: testacr03.azurecr.io/testphp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume
          mountPath: /"/mnt/azure"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk
